//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeTracking.Persistence.Postgresql.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TimeTracking.Persistence.Postgresql.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- clean all entries that have been tracked less than a minute
        ///CREATE OR REPLACE PROCEDURE clean()
        ///LANGUAGE plpgsql
        ///AS $$
        ///
        ///  BEGIN
        ///    DELETE
        ///    FROM tt.time_entry te
        ///    WHERE te.&quot;end&quot; IS NOT NULL
        ///      AND EXTRACT(EPOCH FROM (te.&quot;end&quot; - te.start)) &lt; 60;
        ///  END
        ///
        ///$$.
        /// </summary>
        internal static string Clean {
            get {
                return ResourceManager.GetString("Clean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE OR REPLACE FUNCTION start_tracking
        ///(
        ///  un varchar(64),
        ///  a_id bigint,
        ///  des varchar(256)
        ///)
        ///RETURNS TABLE(activityId bigint, &quot;timestamp&quot; timestamp with time zone)
        ///LANGUAGE plpgsql
        ///AS $$
        ///
        ///  DECLARE startTrackingTimestamp timestamp with time zone = now() at time zone &apos;utc&apos;;
        ///
        ///  BEGIN
        ///
        ///    CALL stop_tracking(un);
        ///    
        ///    -- start tracking an activity
        ///    INSERT INTO tt.time_entry (description, start, activity_id)
        ///      VALUES (des, startTrackingTimestamp, a_id)
        ///    ;
        ///
        ///    RETURN QUER [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StartTracking {
            get {
                return ResourceManager.GetString("StartTracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE OR REPLACE PROCEDURE stop_tracking
        ///(
        ///  un varchar(64)
        ///)
        ///LANGUAGE plpgsql
        ///AS $$
        ///
        ///  DECLARE timestamp timestamp with time zone = now() at time zone &apos;utc&apos;;
        ///
        ///  BEGIN
        ///      
        ///    -- stop tracking the previous active activity
        ///    UPDATE tt.time_entry AS t
        ///      SET
        ///        &quot;end&quot; = timestamp
        ///      FROM tt.users u
        ///        INNER JOIN tt.workspace ws ON ws.id = u.active_workspace_id
        ///        INNER JOIN tt.activities a ON a.workspace_id = ws.id
        ///      WHERE a.id = t.activity_id AND u.username = u [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StopTracking {
            get {
                return ResourceManager.GetString("StopTracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE OR REPLACE PROCEDURE update_active_workspace(
        ///  workspace_id bigint,
        ///  un varchar(64)
        ///)
        ///  LANGUAGE plpgsql
        ///AS
        ///$$
        ///
        ///DECLARE
        ///  timestamp      timestamp with time zone = now() at time zone &apos;utc&apos;;
        ///  DECLARE sideId int;
        ///
        ///BEGIN
        ///
        ///  -- get the current active side id from the entries
        ///  SELECT
        ///      coalesce(a.side_id, 0)
        ///    INTO sideId
        ///    FROM tt.users u
        ///         INNER JOIN tt.workspace ws ON ws.id = u.active_workspace_id
        ///         INNER JOIN tt.activities a ON a.workspace_id = ws.id
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UpdateActiveWorkspace {
            get {
                return ResourceManager.GetString("UpdateActiveWorkspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE OR REPLACE FUNCTION update_dice_side_selection
        ///(
        ///  dSId int,
        ///  un varchar(64)
        ///)
        ///RETURNS TABLE(activityId bigint, &quot;timestamp&quot; timestamp)
        ///LANGUAGE plpgsql
        ///AS $$
        ///
        ///  DECLARE timestamp timestamp with time zone = now() at time zone &apos;utc&apos;;
        ///  DECLARE activityId bigint = 0;
        ///
        ///  BEGIN
        ///
        ///    CALL stop_tracking(un);
        ///
        ///    -- start tracking a new activity
        ///    IF NOT dSId = 0 THEN
        ///
        ///      SELECT a.id
        ///        INTO activityId
        ///          FROM tt.users u
        ///            INNER JOIN tt.workspace ws ON ws.id [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UpdateActivityAssignment {
            get {
                return ResourceManager.GetString("UpdateActivityAssignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE OR REPLACE FUNCTION update_dice_side_selection
        ///(
        ///  dSId int,
        ///  un varchar(64)
        ///)
        ///RETURNS TABLE(activityId bigint, &quot;timestamp&quot; timestamp)
        ///LANGUAGE plpgsql
        ///AS $$
        ///
        ///  DECLARE timestamp timestamp with time zone = now() at time zone &apos;utc&apos;;
        ///  DECLARE activityId bigint = 0;
        ///
        ///  BEGIN
        ///  
        ///    CALL stop_tracking(un);
        ///  
        ///    -- start tracking a new activity
        ///    IF NOT dSId = 0 THEN
        ///       
        ///      SELECT a.id
        ///        INTO activityId
        ///          FROM tt.users u
        ///            INNER JOIN tt.workspace  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UpdateDiceSideSelection {
            get {
                return ResourceManager.GetString("UpdateDiceSideSelection", resourceCulture);
            }
        }
    }
}
