// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TimeTracking.Persistence.Postgresql;

#nullable disable

namespace TimeTracking.Persistence.Postgresql.Migrations
{
    [DbContext(typeof(PostgresqlContext))]
    [Migration("20250529081559_Migration00Initial")]
    partial class Migration00Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TimeTracking.Persistence.Entities.Activity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("ActivityName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("activity_name");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("description");

                    b.Property<byte?>("SideId")
                        .HasColumnType("smallint")
                        .HasColumnName("side_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("WorkspaceId");

                    b.ToTable("activities", "tt");
                });

            modelBuilder.Entity("TimeTracking.Persistence.Entities.TimeEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("ActivityId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("End")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end");

                    b.Property<DateTime?>("Start")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.ToTable("time_entry", "tt");
                });

            modelBuilder.Entity("TimeTracking.Persistence.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid?>("ActiveWorkspaceId")
                        .IsRequired()
                        .HasColumnType("uuid");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("password");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.ToTable("users", "tt");
                });

            modelBuilder.Entity("TimeTracking.Persistence.Entities.Workspace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid?>("ActiveWorkspaceUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("description");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ActiveWorkspaceUserId");

                    b.HasIndex("UserId");

                    b.ToTable("workspace", "tt");
                });

            modelBuilder.Entity("TimeTracking.Persistence.Entities.Activity", b =>
                {
                    b.HasOne("TimeTracking.Persistence.Entities.User", "User")
                        .WithMany("Activities")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TimeTracking.Persistence.Entities.Workspace", "Workspace")
                        .WithMany("Activities")
                        .HasForeignKey("WorkspaceId");

                    b.Navigation("User");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("TimeTracking.Persistence.Entities.TimeEntry", b =>
                {
                    b.HasOne("TimeTracking.Persistence.Entities.Activity", "Activity")
                        .WithMany("TimeEntries")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");
                });

            modelBuilder.Entity("TimeTracking.Persistence.Entities.Workspace", b =>
                {
                    b.HasOne("TimeTracking.Persistence.Entities.User", "ActiveWorkspaceUser")
                        .WithMany()
                        .HasForeignKey("ActiveWorkspaceUserId");

                    b.HasOne("TimeTracking.Persistence.Entities.User", null)
                        .WithOne("ActiveWorkspace")
                        .HasForeignKey("TimeTracking.Persistence.Entities.Workspace", "Id")
                        .HasPrincipalKey("TimeTracking.Persistence.Entities.User", "ActiveWorkspaceId");

                    b.HasOne("TimeTracking.Persistence.Entities.User", "User")
                        .WithMany("Workspaces")
                        .HasForeignKey("UserId");

                    b.Navigation("ActiveWorkspaceUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TimeTracking.Persistence.Entities.Activity", b =>
                {
                    b.Navigation("TimeEntries");
                });

            modelBuilder.Entity("TimeTracking.Persistence.Entities.User", b =>
                {
                    b.Navigation("ActiveWorkspace");

                    b.Navigation("Activities");

                    b.Navigation("Workspaces");
                });

            modelBuilder.Entity("TimeTracking.Persistence.Entities.Workspace", b =>
                {
                    b.Navigation("Activities");
                });
#pragma warning restore 612, 618
        }
    }
}
