// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TimeTracking.Persistence.Postgresql;

#nullable disable

namespace TimeTracking.Persistence.Postgresql.Migrations
{
    [DbContext(typeof(PostgresqlContext))]
    partial class PostgresqlContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TimeTracking.Persistence.Entities.Activity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ActivityName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("activity_name");

                    b.Property<int>("Color")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("description");

                    b.Property<byte?>("SideId")
                        .HasColumnType("smallint")
                        .HasColumnName("side_id");

                    b.Property<long?>("workspace_id")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("workspace_id");

                    b.ToTable("activities", "tt");
                });

            modelBuilder.Entity("TimeTracking.Persistence.Entities.TimeEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("End")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end");

                    b.Property<DateTime?>("Start")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start");

                    b.Property<long>("activity_id")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("activity_id");

                    b.ToTable("time_entry", "tt");
                });

            modelBuilder.Entity("TimeTracking.Persistence.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ActiveWorkspaceId")
                        .HasColumnType("bigint")
                        .HasColumnName("active_workspace_id");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("password");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("ActiveWorkspaceId")
                        .IsUnique();

                    b.ToTable("users", "tt");
                });

            modelBuilder.Entity("TimeTracking.Persistence.Entities.Workspace", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("description");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.Property<long?>("fk_user_id")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("fk_user_id");

                    b.ToTable("workspace", "tt");
                });

            modelBuilder.Entity("TimeTracking.Persistence.Entities.Activity", b =>
                {
                    b.HasOne("TimeTracking.Persistence.Entities.Workspace", "Workspace")
                        .WithMany("Activities")
                        .HasForeignKey("workspace_id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("TimeTracking.Persistence.Entities.TimeEntry", b =>
                {
                    b.HasOne("TimeTracking.Persistence.Entities.Activity", "Activity")
                        .WithMany("TimeEntries")
                        .HasForeignKey("activity_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");
                });

            modelBuilder.Entity("TimeTracking.Persistence.Entities.User", b =>
                {
                    b.HasOne("TimeTracking.Persistence.Entities.Workspace", "ActiveWorkspace")
                        .WithOne("ActiveWorkspaceUser")
                        .HasForeignKey("TimeTracking.Persistence.Entities.User", "ActiveWorkspaceId");

                    b.Navigation("ActiveWorkspace");
                });

            modelBuilder.Entity("TimeTracking.Persistence.Entities.Workspace", b =>
                {
                    b.HasOne("TimeTracking.Persistence.Entities.User", "User")
                        .WithMany("Workspaces")
                        .HasForeignKey("fk_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TimeTracking.Persistence.Entities.Activity", b =>
                {
                    b.Navigation("TimeEntries");
                });

            modelBuilder.Entity("TimeTracking.Persistence.Entities.User", b =>
                {
                    b.Navigation("Workspaces");
                });

            modelBuilder.Entity("TimeTracking.Persistence.Entities.Workspace", b =>
                {
                    b.Navigation("ActiveWorkspaceUser");

                    b.Navigation("Activities");
                });
#pragma warning restore 612, 618
        }
    }
}
